name: Get Runner IP Address

on: [push]

jobs:
  get_ip_address:
    runs-on: ubuntu-latest
    
    steps:
    - name: Show Runner IP Address
      run: |
        echo "Runner IP Address: ${{ runner.ip }}"
