name: Add Inbound NSG Rule and SSH into Azure VM

on:
  push:
    branches:
      - main

jobs:
  get_runner_ip:
    runs-on: ubuntu-latest
    outputs:
      runner_ip: ${{ steps.get_ip.outputs.runner_ip }}
    steps:
    - name: Get Runner IP
      id: get_ip
      run: echo "::set-output name=runner_ip::$(hostname -I | awk '{print $1}')"

  add_nsg_rule_and_ssh:
    runs-on: ubuntu-latest
    needs: get_runner_ip
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Inbound NSG Rule
      uses: azure/cli@v1
      with:
        azcliversion: 2.32.0
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_SP_APP_ID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az network nsg rule create --name MyInboundNSGRule --nsg-name test-nsg --resource-group test --priority 100 --destination-port-range 22 --protocol tcp --access Allow --source-address-prefixes ${{ needs.get_runner_ip.outputs.runner_ip }} --description "Allow SSH traffic from GitHub Actions runner"
    
    - name: SSH into Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_PUBLIC_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Your SSH commands go here
          echo "SSH connection successful" > test1.txt
  delete_nsg_rule:
    runs-on: ubuntu-latest
    needs: [add_nsg_rule_and_ssh]
    steps:
    - name: Delete Inbound NSG Rule
      uses: azure/cli@v1
      with:
        azcliversion: 2.32.0
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_SP_APP_ID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az network nsg rule delete --name MyInboundNSGRule --nsg-name test-nsg --resource-group test        
