name: Get Runner IP

on:
  push:
    branches:
      - main

jobs:
  get_ip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Runner IP
      run: |
        RUNNER_IP=$(curl -s https://api.github.com/meta | jq -r '.actions[].runner_ip')
          echo "::set-output name=runner_ip::$RUNNER_IP"
