name: Get Runner IP Address

on: [push]

jobs:
  get_ip_address:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Docker
      uses: actions/setup-docker@v2
      
    - name: Get Runner IP Address
      id: runner_ip
      run: |
        # Fetch the network interfaces and IP addresses
        ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1
        echo "::set-output name=runner_ip::$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)"
      
    - name: Display Runner IP Address
      run: |
        echo "Runner IP Address: ${{ steps.runner_ip.outputs.runner_ip }}"
